//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_tekara
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.products = new HashSet<product>();
            this.shipping_card = new HashSet<shipping_card>();
        }
    
        public int cust_ID { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> b_date { get; set; }
        public Nullable<bool> is_seller { get; set; }
        public string username { get; set; }
        public string pass { get; set; }
        public byte[] cust_img { get; set; }
        public Nullable<bool> is_trusted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipping_card> shipping_card { get; set; }
    }
}
