//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_tekara
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.shipping_card = new HashSet<shipping_card>();
        }
    
        public int p_ID { get; set; }
        public string p_name { get; set; }
        public string p_cat { get; set; }
        public string p_desc { get; set; }
        public int p_price { get; set; }
        public byte[] p_img { get; set; }
        public int seller_ID { get; set; }
        public Nullable<bool> is_solled { get; set; }
    
        public virtual customer customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shipping_card> shipping_card { get; set; }
    }
}
