//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_tekara
{
    using System;
    using System.Collections.Generic;
    
    public partial class shipping_card
    {
        public int ID { get; set; }
        public int p_ID { get; set; }
        public int buyer_ID { get; set; }
        public int seller_ID { get; set; }
        public bool is_approved { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
